//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1061 with alias "hasTextAndMedia"
	/// <summary>_HasTextAndMedia</summary>
	public partial interface IHasTextAndMedia : IPublishedContent
	{
		/// <summary>Image</summary>
		IPublishedContent TextMediaImage { get; }

		/// <summary>Summary</summary>
		string TextMediaSummary { get; }

		/// <summary>Title</summary>
		string TextMediaTitle { get; }
	}

	/// <summary>_HasTextAndMedia</summary>
	[PublishedContentModel("hasTextAndMedia")]
	public partial class HasTextAndMedia : PublishedContentModel, IHasTextAndMedia
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hasTextAndMedia";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HasTextAndMedia(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HasTextAndMedia, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("textMediaImage")]
		public IPublishedContent TextMediaImage
		{
			get { return GetTextMediaImage(this); }
		}

		/// <summary>Static getter for Image</summary>
		public static IPublishedContent GetTextMediaImage(IHasTextAndMedia that) { return that.GetPropertyValue<IPublishedContent>("textMediaImage"); }

		///<summary>
		/// Summary
		///</summary>
		[ImplementPropertyType("textMediaSummary")]
		public string TextMediaSummary
		{
			get { return GetTextMediaSummary(this); }
		}

		/// <summary>Static getter for Summary</summary>
		public static string GetTextMediaSummary(IHasTextAndMedia that) { return that.GetPropertyValue<string>("textMediaSummary"); }

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("textMediaTitle")]
		public string TextMediaTitle
		{
			get { return GetTextMediaTitle(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetTextMediaTitle(IHasTextAndMedia that) { return that.GetPropertyValue<string>("textMediaTitle"); }
	}
}
